### ISSUE TITLE
dirname doesn't take multiple paths on every platform

### ISSUE THREAD

**Issue by Sjord** [returntocorp/semgrep-grammars#19]
In [Makefile.common](https://github.com/returntocorp/semgrep-grammars/blob/master/src/Makefile.common#L28):

```
	for dir in $$(find . | grep 'grammar.js$$' | xargs dirname); do \
```

This may pass multiple arguments to `dirname`, in case multiple `grammar.js` files are found. On MacOS, dirname only takes a single argument. The `dirname` command will fail and the for loop does nothing.

A solution would be to call dirname on every argument, for example using `xargs -L1`.

**Comment by aryx** [comment]
@mjambon can you look at that?

**Comment by mjambon** [comment]
I'll fix that. Thank you @Sjord.

Unrelated note: we're moving semgrep-grammars to the ocaml-tree-sitter repo. Same place, except it's no longer a git submodule.
